-- Create the table for contact messages
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.messages enable row level security;

-- Create a policy to allow anyone (anon) to insert messages
create policy "Enable insert for everyone" 
on public.messages 
for insert 
with check (true);

-- Create a policy to allow only authenticated users (you) to select/read messages
-- This prevents random people from reading your database via the API
create policy "Enable read access for authenticated users only" 
on public.messages 
for select 
using (auth.role() = 'authenticated');
